"""
Validate traces generated by the realworld_research_agent.py
Queries the local storage and API to assert AgentTrace caught everything.
"""

import os
import sqlite3
import sys

DB_PATH = os.path.join(os.path.dirname(__file__), "..", "..", ".agenttrace.db")


def verify():
    print("🔍 Verifying Traces...")

    if not os.path.exists(DB_PATH):
        print(f"❌ ERROR: Database not found at {DB_PATH}")
        sys.exit(1)

    conn = sqlite3.connect(DB_PATH)
    conn.row_factory = sqlite3.Row
    cursor = conn.cursor()

    # 1. Total steps in the database
    cursor.execute("SELECT COUNT(*) FROM steps")
    total_steps = cursor.fetchone()[0]
    print(f"✅ DB has {total_steps} total steps")

    # 2. Get the trace ID with the most steps (the main LangGraph workflow)
    cursor.execute(
        "SELECT trace_id, COUNT(*) as c FROM steps GROUP BY trace_id ORDER BY c DESC"
    )
    trace_counts = cursor.fetchall()
    if not trace_counts:
        print("❌ ERROR: No steps found.")
        sys.exit(1)

    if len(trace_counts) > 1:
        print(
            f"❌ ERROR: Found {len(trace_counts)} different trace IDs! Steps should be unified under a single trace."
        )
        for row in trace_counts:
            print(f"  - Trace {row['trace_id']}: {row['c']} steps")
        sys.exit(1)

    trace_id = trace_counts[0]["trace_id"]
    print(
        f"✅ Found exact single unified trace: {trace_id} with {trace_counts[0]['c']} steps"
    )

    # 3. Check types in this specific trace
    cursor.execute(
        "SELECT type, name, outputs FROM steps WHERE trace_id = ? ORDER BY timestamp ASC",
        (trace_id,),
    )
    steps = cursor.fetchall()

    if len(steps) < 5:
        print(
            f"❌ ERROR: Expected >= 5 steps for a full LangGraph run, got {len(steps)}."
        )
        sys.exit(1)
    else:
        print(f"✅ Found {len(steps)} steps in the trace (expected >= 5).")

    types = set(s["type"] for s in steps)
    if "llm_call" not in types or "tool_execution" not in types:
        print(
            f"❌ ERROR: Trace is missing either llm_calls or tool_executions. Types found: {types}"
        )
        sys.exit(1)
    else:
        print("✅ Captured both llm_call and tool_execution types automatically.")

    if "chain" in types:
        print(
            "❌ ERROR: Trace contains internal 'chain' spans which should be filtered out!"
        )
        sys.exit(1)
    else:
        print("✅ Verified that internal 'chain' noise was successfully filtered.")

    # 4. Check tool names
    tool_names = set(s["name"] for s in steps if s["type"] == "tool_execution")
    expected_tool = "write_final_report"
    if expected_tool not in tool_names:
        print(f"❌ ERROR: Agent didn't use '{expected_tool}'. Used tools: {tool_names}")
        sys.exit(1)
    else:
        print(f"✅ Detected usage of custom tool: {expected_tool}")

    # 5. Check report was written
    if os.path.exists("quantum_research_report.md"):
        print("✅ Report file quantum_research_report.md generated on disk.")
    else:
        print("❌ ERROR: Output file not created.")
        sys.exit(1)

    print("\n🎉 ALL TRACE VERIFICATIONS PASSED!")


if __name__ == "__main__":
    verify()
